### ISSUE TITLE
Formatting doesn't seem to matter

### ISSUE THREAD

**Issue by feakuru** [timgilbert/cljs-pikaday#7]
Passing `:format`, `:toString` and `:parse` in `:pikaday-attrs` seems to have no effect. Am I doing it wrong?

**Comment by halcyon** [comment]
@feakuru I was able to get `{:pkaday-attrs {:format "moment-js-format-string-here"}}` working by adding https://clojars.org/cljsjs/moment to my project.clj/deps.edn and requiring `[cljsjs.moment]` in the `ns` form the component is defined in.
